config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get '/profile', to: 'user#show'
  resources :companies
  resources :games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies
  has_many :reviews, as: :reviewable

  validates :name, :country, presence: true
  validates :name, uniqueness: true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres
  has_many :expansions, class_name: 'Game', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'Game', optional: true
  has_many :reviews, as: :reviewable
  enum category: { main_game: 0, expansion: 1 }

  validates :name, :category, presence: true
  validates :name, uniqueness: true
  validates :rating, allow_nil: true, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100,
  }

  validate :parent_exists

  private
  def parent_exists
    if category == 'expansion' && Game.find_by(id: parent_id).nil?
      errors.add(:parent_id, 'Game does not exist')
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games

  validates :name, presence: true, uniqueness: true
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  belongs_to :company
  belongs_to :game

  validates :developer, :publisher, inclusion: { in: [true, false] }
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_and_belongs_to_many :games
  enum category: {
    console: 0,
    arcade: 1,
    platform: 2,
    operating_system: 3,
    portable_console: 4,
    computer: 5,
  }

  validates :name, :category, presence: true
  validates :name, uniqueness: true

  def es
    self.valid?
    p self.errors.messages
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :reviewable, polymorphic: true

  validates :title, :body, presence: true
  validates :title, length: { maximum: 40 }, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews

  validates :username, :email, presence: true, uniqueness: true
  validate :older_than_16

  private
  def older_than_16
    if birth_date >= 16.year.ago.to_date
      errors.add(:birth_date, 'You should be 16 years old to create an account')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :birth_date])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path
  end

  private
  def company_params
    params
      .require(:company)
      .permit(:name, :description, :start_date, :country)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to @game
    else
      render :edit
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end

  private
  def game_params
    params
      .require(:game)
      .permit(:name, :summary, :release_date, :category, :rating, :parent_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'welcome'

  def welcome
  end

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to games_path
    else
      redirect_to login_path, notice: 'Username or password invalid'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/welcome'
  end

  skip_before_action :authorized, only: [:new, :create, :welcome]
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'welcome'

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to games_path
    else
      render :new
    end
  end

  skip_before_action :authorized, only: [:new, :create]

  private
  def user_params
    params
      .require(:user)
      .permit(:username, :password, :email, :birth_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_edit_form.html.erb
<%= form_for(@company) do |f| %>
  <ul>
    <% @company.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit this Company</h1>

<%= render partial: 'edit_form' %>

<%= link_to 'Back to Companies', companies_path %>

app/views/companies/index.html.erb
<h1>All the Companies</h1>
<%= link_to 'New Company', new_company_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.country %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>Create a New Company</h1>
<%= form_for(@company) do |f| %>
  <ul>
    <% @company.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<p><%= @company.description %></p>
<ul>
  <li>Start Date: <%= @company.start_date %></li>
  <li>Country: <%= @company.country %></li>
</ul>
<p><%= link_to 'Back to Companies', companies_path %></p>
<p>
  <%=
    link_to 'Delete this Company', company_path(@company), method: :delete, data: {
      confirm: 'Do you really want to delete this company?',
    }
  %>
</p>

app/views/games/_edit_form.html.erb
<%= form_for(@game) do |f| %>
  <ul>
  <% @game.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </p>
  <p>
    <%= f.label :release_date %><br />
    <%= f.text_field :release_date %>
  </p>
  <p>
    <%= f.label :category %><br />
    <%= f.select :category, Game.categories.keys %>
  </p>
  <p>
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </p>
  <p>
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/games/edit.html.erb
<h1>Edit this Game</h1>

<%= render partial: 'edit_form' %>

<%= link_to "Back to Games", games_path %>

app/views/games/index.html.erb
<h1>All the Games</h1>

<%= link_to 'New Game', new_game_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.rating %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>Create a New Game</h1>

<%= render partial: 'edit_form' %>

<%= link_to 'Back to Games', games_path %>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<p><%= @game.summary %></p>
<ul>
  <li>Rating: <%= @game.rating %></li>
  <li>Category: <%= @game.category %></li>
  <li>Release Date: <%= @game.release_date %></li>
  <li>Platform(s): <%= @game.platforms.map { |plat| plat.name }.join(', ') %></li>
  <li>Genre(s): <%= @game.genres.map { |gen| gen.name }.join(', ') %></li>
</ul>
<p><%= link_to 'Back to Games', games_path %></p>
<p>
  <%=
    link_to 'Delete this Game', game_path(@game), method: :delete, data: {
      confirm: 'Do you really want to delete this game?',
    }
  %>
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% if user_signed_in? %>
  <p><%= link_to 'Profile', profile_path %></p>
  <p><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></p>
<% else %>
  <p><%= link_to 'Sign In', new_user_session_path %></p>
  <p><%= link_to 'Sign Up', new_user_registration_path %></p>
<% end %>

app/views/user/show.html.erb
<h1>User Profile</h1>
<p>Find me in app/views/user/show.html.erb</p>

<p>Username: <%= @user.username %></p>
<p>Email: <%= @user.email %></p>
<p>Birth Date: <%= @user.birth_date %></p>

<p><%= link_to 'Back to Home', root_path %></p>
<p><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

<%= form_for @user do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :birth_date %><br>
  <%= f.text_field :birth_date %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.submit %>
<% end %>